# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bverdeci <marvin@42lausanne.ch>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/06/25 09:52:59 by bverdeci          #+#    #+#              #
#    Updated: 2022/06/25 18:31:54 by bverdeci         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = ft_putchar.c ft_strstr.c dict.c ft_atoi.c ft_strlen.c main.c

GCC = gcc

CFLAGS = -Wall -Werror -Wextra

NAME = rush-02

all:
	 ${GCC} ${CFLAGS} ${SRC} -o ${NAME}
clean:
	rm -rf rush-02
fclean: clean
